name: Print Hello World
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: "Add Numbers"
        run: echo $((1+2))
      - name: "Run JavaScript"
        run: node hello.js